# Generated by Django 5.0.4 on 2024-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify_email',
            field=models.BooleanField(default=False, verbose_name='подтвержденный эмеил'),
        ),
    ]
