# Generated by Django 5.0.4 on 2024-05-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_posts_time_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='description',
            new_name='text',
        ),
    ]
