# Generated by Django 5.0.4 on 2024-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_description_postcomment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
