# Generated by Django 5.0.4 on 2024-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_postcomment_is_published_posts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='просмотры'),
        ),
    ]
