# Generated by Django 5.0.4 on 2024-04-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Шапка Страницы')),
                ('text_to_form', models.CharField(max_length=200, verbose_name='Заглавление к пунктам')),
                ('text_title_form', models.CharField(max_length=200, verbose_name='Текст перед формой')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Страница Контакты',
            },
        ),
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=50, verbose_name='Первое поле')),
                ('first_name', models.CharField(default='Максим', max_length=50, verbose_name='Заполнение первого поля')),
                ('email', models.CharField(default='Эмеил', max_length=50, verbose_name='Второе поле')),
                ('email_fill', models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Заполнение второго поля')),
                ('tel', models.CharField(default='Номер телефона', max_length=40, verbose_name='Третье поле')),
                ('tel_fill', models.CharField(default='+7(000)000-00-00', max_length=18, verbose_name='Заполнение третьего поля')),
                ('question', models.CharField(default='Ваш вопрос', max_length=50, verbose_name='Четвертое поле')),
                ('ruls', models.CharField(default='Правила обработки информации', max_length=50, verbose_name='Правила')),
                ('button', models.CharField(default='Отправить заявку', max_length=50, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма контактов',
            },
        ),
        migrations.CreateModel(
            name='InformationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши контакты:', max_length=100, verbose_name='Шапка контактов')),
                ('email', models.CharField(default='Эмеил:', max_length=20, verbose_name='Шапка эмеила')),
                ('email_value', models.EmailField(max_length=254, verbose_name='Значение Эмеила')),
                ('tel', models.CharField(default='Телефон:', max_length=50, verbose_name='Шапка телефона')),
                ('tel_value', models.CharField(max_length=50, verbose_name='Значение телефона')),
                ('fax', models.CharField(default='Факс:', max_length=50, verbose_name='Шапка факса')),
                ('fax_value', models.CharField(max_length=50, verbose_name='Значение факса')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='StatementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_form', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formcontact', verbose_name='Пункты причин для формы')),
            ],
            options={
                'verbose_name': 'Причины',
                'verbose_name_plural': 'Причины из формы',
            },
        ),
        migrations.CreateModel(
            name='StatementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact', verbose_name='Пункты причин заявления')),
            ],
            options={
                'verbose_name': 'Причины',
                'verbose_name_plural': 'Список причин для страницы',
            },
        ),
    ]
