# Generated by Django 5.0.4 on 2024-04-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMainHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('mask_search', models.CharField(max_length=50)),
                ('button', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка Страницы',
            },
        ),
        migrations.CreateModel(
            name='NavList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Кнопки шапки навигации')),
                ('url', models.URLField(unique=True)),
                ('nav_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.navmainhome', verbose_name='Поле Навигации')),
            ],
            options={
                'verbose_name': 'Пунк',
                'verbose_name_plural': 'Пункты Навигации',
            },
        ),
    ]
