# Generated by Django 5.0.4 on 2024-04-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_navmainhome_navlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlist',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
