# Generated by Django 5.0.4 on 2024-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_navlist_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Каталог товаров', max_length=50, verbose_name='Заглавление')),
            ],
        ),
    ]
