# Generated by Django 5.0.4 on 2024-04-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_navleft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navleft',
            options={'verbose_name': 'Оглавление', 'verbose_name_plural': 'Оглавление левого бара'},
        ),
    ]
