# Generated by Django 5.0.4 on 2024-04-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_navleft_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новинки', max_length=50, verbose_name='Заглавление')),
            ],
            options={
                'verbose_name': 'Оглавление',
                'verbose_name_plural': 'Оглавление правого бара',
            },
        ),
    ]
