# Generated by Django 5.0.4 on 2024-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_footer_footerbloks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterBloks',
            new_name='FooterBlocks',
        ),
    ]
