# Generated by Django 5.0.4 on 2024-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_footerbloks_footerblocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerblocks',
            name='url',
            field=models.SlugField(blank=True, max_length=256, verbose_name='Адресс блока'),
        ),
    ]
