# Generated by Django 5.0.4 on 2024-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_footerblocks_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление блока')),
                ('url', models.SlugField(max_length=256, unique=True)),
                ('button', models.CharField(max_length=20, verbose_name='Имя кнопки')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'Доманшняя страница',
            },
        ),
        migrations.AlterField(
            model_name='footer',
            name='url_policy',
            field=models.SlugField(default='policy', max_length=256),
        ),
        migrations.AlterField(
            model_name='footerblocks',
            name='url',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Адресс блока'),
        ),
    ]
