# Generated by Django 5.0.4 on 2024-04-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_footer_url_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navlist',
            options={'ordering': ['pk'], 'verbose_name': 'Пунк', 'verbose_name_plural': 'Пункты Навигации'},
        ),
    ]
