# Generated by Django 5.0.4 on 2024-05-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_navlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'страница', 'verbose_name_plural': 'Домашняя страница'},
        ),
        migrations.CreateModel(
            name='BasePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.footer')),
                ('footer_block', models.ManyToManyField(to='home.footerblocks')),
                ('home_page', models.ManyToManyField(to='home.homepage')),
                ('nav_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.navmainhome')),
                ('nav_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.navleft')),
                ('nav_list', models.ManyToManyField(to='home.navlist')),
                ('nav_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.navright')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'База',
            },
        ),
    ]
