# Generated by Django 5.0.4 on 2024-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_navlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlist',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
