# Generated by Django 5.0.4 on 2024-04-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Компания')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'компаний',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='catalog.companies', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
