# Generated by Django 5.0.4 on 2024-04-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_companies_product_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='county',
            new_name='country',
        ),
    ]
