# Generated by Django 5.0.4 on 2024-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_release_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='price_quantity_gte-0',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0), ('price__gte', 0), ('quantity__gte', 0)), name='price_quantity_gte_discount__gte-0'),
        ),
    ]
