# Generated by Django 5.0.4 on 2024-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_companies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_column='category', max_length=50, primary_key=True, serialize=False, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company',
            field=models.CharField(db_column='company', max_length=100, primary_key=True, serialize=False, verbose_name='Компания'),
        ),
    ]
