# Generated by Django 5.0.4 on 2024-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_companies_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='category',
        ),
        migrations.AddField(
            model_name='companies',
            name='category',
            field=models.ManyToManyField(to='catalog.category', verbose_name='Категории компании'),
        ),
    ]
