# Generated by Django 5.0.4 on 2024-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_category_alter_companies_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Шапка Страницы')),
                ('text_to_form', models.CharField(max_length=200, verbose_name='Заглавление к пунктам')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Страница Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=50, verbose_name='Первое поле')),
                ('first_name', models.CharField(default='Максим', max_length=50, verbose_name='Заполнение первого поля')),
                ('email', models.CharField(default='Эмеил', max_length=50, verbose_name='Второе поле')),
                ('email_fill', models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Заполнение второго поля')),
                ('tel', models.CharField(default='Номер телефона', max_length=40, verbose_name='Третье поле')),
                ('tel_fill', models.CharField(default='+7(000)000-00-00', max_length=18, verbose_name='Заполнение третьего поля')),
                ('question', models.CharField(default='Ваш вопрос', max_length=50, verbose_name='Четвертое поле')),
                ('ruls', models.CharField(default='Правила обработки информации', max_length=50, verbose_name='Правила')),
                ('button', models.CharField(default='Отправить заявку', max_length=50, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма контактов',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'катерогии', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'компании', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.CreateModel(
            name='StatementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_form', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.contactform', verbose_name='Пункты причин для формы')),
            ],
            options={
                'verbose_name': 'Причины',
                'verbose_name_plural': 'Причины из формы',
            },
        ),
        migrations.CreateModel(
            name='StatementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.contact', verbose_name='Пункты причин заявления')),
            ],
            options={
                'verbose_name': 'Причины',
                'verbose_name_plural': 'Список причин для страницы',
            },
        ),
    ]
