# Generated by Django 5.0.4 on 2024-04-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_companies_category_companies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='url',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50, verbose_name='Под категория')),
                ('url', models.SlugField(default=None, max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория')),
            ],
        ),
    ]
