# Generated by Django 5.0.4 on 2024-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contact_contactform_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши контакты:', max_length=100, verbose_name='Шапка контактов')),
                ('email', models.CharField(default='Эмеил:', max_length=20, verbose_name='Шапка эмеила')),
                ('email_value', models.EmailField(max_length=254, verbose_name='Значение Эмеила')),
                ('tel', models.CharField(default='Телефон:', max_length=50, verbose_name='Шапка телефона')),
                ('tel_value', models.CharField(max_length=50, verbose_name='Значение телефона')),
                ('fax', models.CharField(default='Факс:', max_length=50, verbose_name='Шапка факса')),
                ('fax_value', models.CharField(max_length=50, verbose_name='Значение факса')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
