# Generated by Django 5.0.4 on 2024-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_companies_url_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'под катерогии', 'verbose_name_plural': 'Под Категории'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='url',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
