# Generated by Django 5.0.4 on 2024-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_subcategory_options_alter_companies_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='url',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
