# Generated by Django 5.0.4 on 2024-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_informationcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text_title_form',
            field=models.CharField(default=None, max_length=200, verbose_name='Текст перед формой'),
            preserve_default=False,
        ),
    ]
