# Generated by Django 5.0.4 on 2024-04-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_category_url_remove_companies_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default=None, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='url',
            field=models.SlugField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50, verbose_name='Под категория')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'под катерогии',
                'verbose_name_plural': 'Под Категории',
            },
        ),
    ]
