# Generated by Django 5.0.4 on 2024-04-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_contact_text_title_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='FormContact',
        ),
    ]
