# Generated by Django 5.0.4 on 2024-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_button',
            field=models.CharField(default='Подробнее', max_length=20, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
