# Generated by Django 5.0.4 on 2024-04-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_filter', models.CharField(max_length=50, unique=True, verbose_name='тип фильтров')),
            ],
            options={
                'verbose_name': 'тип фильтров',
                'verbose_name_plural': 'фильтры',
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_filter', models.CharField(max_length=50, unique=True, verbose_name='фильтр')),
                ('url', models.SlugField(max_length=256, unique=True)),
                ('type_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.topfilters', verbose_name='тип фильтра')),
            ],
            options={
                'verbose_name': 'фильтры',
                'verbose_name_plural': 'фильтры',
            },
        ),
    ]
