# Generated by Django 5.0.4 on 2024-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_topfilters_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topfilters',
            options={'verbose_name': 'тип фильтров', 'verbose_name_plural': 'тип фильтров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=256),
        ),
    ]
