# Generated by Django 5.0.4 on 2024-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='companies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company', verbose_name='изображение'),
        ),
    ]
