# Generated by Django 5.0.4 on 2024-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_category_image_companies_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'катерогии', 'verbose_name_plural': 'Категории'},
        ),
    ]
