# Generated by Django 5.0.6 on 2024-05-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_number', models.SlugField(verbose_name='номер версии')),
                ('os_name', models.CharField(max_length=256, verbose_name='название версии')),
                ('actual_os', models.BooleanField(verbose_name='признак актуальности')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
